version = 5.5.0
archive_dir = /etc/letsencrypt/archive/admin.eduvers.site
cert = /etc/letsencrypt/live/admin.eduvers.site/cert.pem
privkey = /etc/letsencrypt/live/admin.eduvers.site/privkey.pem
chain = /etc/letsencrypt/live/admin.eduvers.site/chain.pem
fullchain = /etc/letsencrypt/live/admin.eduvers.site/fullchain.pem
[renewalparams]
account = 3f147683c4aea637839ef04fa50e2333
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-05-03T15:15:05
